common/models/Comment.php
<?php

namespace common\models;

use common\models\Article;
use common\models\User;
use Yii;

/**
 * This is the model class for table "comment".
 *
 * @property int $id
 * @property string $text
 * @property int $user_id
 * @property int $article_id
 * @property int $status
 *
 * @property Article $article
 * @property User $user
 */
class Comment extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'comment';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['text'], 'string'],
            [['user_id', 'article_id', 'status'], 'integer'],
            [['article_id'], 'exist', 'skipOnError' => true, 'targetClass' => Article::className(), 'targetAttribute' => ['article_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'text' => 'Text',
            'user_id' => 'User ID',
            'article_id' => 'Article ID',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticle()
    {
        return $this->hasOne(Article::className(), ['id' => 'article_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getDate(){
        return Yii::$app->formatter->asDate($this->date);
    }

    public function isAllowed(){
        return $this->status;
    }

    public function allow(){
        $this->status = 1;

        return $this->save(false);
    }

    public function disallow(){

        $this->status = 0;

        return $this->save(false);

    }
}

frontend/models/CommentForm.php
<?php

namespace app\models;

use common\models\Comment;
use Yii;
use yii\base\Model;

class CommentForm extends Model{

    public $comment;

    public function rules()
    {
        return [
            [['comment'], 'required'],
            [['comment'], 'string', 'length' => [3, 250]],
        ];
    }

    public function saveComment($article_id){

        $comment = new Comment();

        $comment->text = $this->comment;
        $comment->user_id =Yii::$app->user->id;
        $comment->article_id = $article_id;
        $comment->status = 1;
        $comment->date = date('Y-m-d');

        return $comment->save();
    }
}

backend/controllers/CommentController.php
<?php

namespace backend\controllers;


use yii\web\Controller;
use Yii;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\Comment;

class CommentController extends Controller{

	public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index','delete'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex(){

        $comments = Comment::find()->orderBy('id DESC')->all();
    	

    	return $this->render('index',[
            'comments' => $comments,
        ]);
    }

    public function actionDelete($id = false)
    {
        if (isset($id)) {
            if (User::deleteAll(['in', 'id', $id])) {
                $this->redirect(['index']);
            }
        } else {
            $this->redirect(['index']);
        }
    }
}

backend/views/comment/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Url;
$this->title = 'My Yii Application';
?>
       
        <div class="container" style="height: 100%;margin-top: 0px;padding-top: 115px;padding-bottom: 115px;">
            <!-- row -->
            <div class="row tm-content-row" style="height: 100%; overflow-y: scroll;">
                <div class="col-12 tm-block-col">
                    <div class="tm-bg-primary-dark tm-block tm-block-taller tm-block-scroll" style="height: 100%;">
                        <h2 class="tm-block-title">Фикерләр:</h2>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">№</th>
                                    <th scope="col">Текст</th>
                                    <th scope="col">Фильм</th>
                                    <th scope="col">Кулланучы</th>
                                    <th scope="col">Вакыты</th>
                                    <th scope="col">Статус</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($comments as $comment):?>
                                <tr>
                                    <th scope="row"><b>#<?= $comment->id ?></b></th>
                                    <td><b><?= $comment->text ?></b></td>
                                    <td><b><?= $comment->article->title ?></b></td>
                                    <td><b><?= $comment->user->username ?></b></td>
                                    <td><b><?= $comment->date ?></b></td>
                                    <td>
                                        <?php if($comment->status === 1): ?>
                                            <div class="tm-status-circle moving">
                                        <?php else: ?>
                                            <div class="tm-status-circle cancelled">
                                        <?php endif; ?>
                                    </td>
                                    <td>
                                        <a href="<?= Url::to(['comment/delete', 'id' => $comment->id]) ?>" onclick="return confirm('Вы уверены?')" class="tm-product-delete-link">
                                        <i class="far fa-trash-alt tm-product-delete-icon"></i>
                                        </a>
                                    </td>
                                </tr>   
                            <?php endforeach; ?>
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>