common/models/Category.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property string $title
 * @property string $nick
 *
 * @property Article[] $articles
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'nick'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'nick' => 'Nick',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticles()
    {
        return $this->hasMany(Article::className(), ['category_id' => 'id']);
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\User;
use common\models\Article;
use common\models\Category;
use yii\web\UploadedFile;
use common\models\File;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['logout','index', 'video','add','delete','file','add-file'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['login', 'error','role'],
                        'allow' => true,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $articles = Article::find()->orderBy( 'id DESC')->all();

        return $this->render('index', [
            'articles' => $articles,
        ]);
    }

    public function actionDelete($id = false)
    {
        if (isset($id)) {
            if (Article::deleteAll(['in', 'id', $id])) {
                $this->redirect(['index']);
            }
        } else {
            $this->redirect(['index']);
        }
    }



    public function actionVideo($id)
    {

        $files = File::find()->where(['article_id' => $id])->all();
  
        $category = Category::find()->all();

        $article = Article::findOne($id);

        if($article->load(Yii::$app->request->post())){
            if($article->save())
                return $this->redirect(['site/index']);
                
      }

        return $this->render('video', [
            'article' => $article,
            'category' => $category,
            'files' => $files,
        ]);
    }

    public function actionFile($id){

      $files = File::find()->where(['article_id' => $id])->all();

      $article = File::find()->where(['id' => $id])->one();


      return $this->render('file',[
        'files' => $files,
        'article' => $article,
      ]);
    }

    public function actionAddFile($id){
      
        $model = new File();

        $model->article_id = $id;

        $model->date = date('Y-m-d');

        if($model->load(Yii::$app->request->post())){
          if($model->save()){
            return $this->redirect(['site/file','id'=> $id]);
          }
        }

      return $this->render('add-file',[
        'model' => $model,
      ]);
    }

    public function actionAdd(){

      
      $category = Category::find()->all();

      $model = new Article();
      $model->date = date('Y-m-d');
      $model->viewed = 0;
      if($model->load(Yii::$app->request->post())){
         if($model->validate()){
            $file = UploadedFile::getInstance($model,'image');
              if(file_exists($file)){
                $model->saveImage($this->uploadFile($file));
              }else{
                $model->image = NULL;
              }

              $icon = UploadedFile::getInstance($model,'image_icon');

              if(file_exists($icon)){
                $model->saveImageIcon($this->uploadFileIcon($icon));
              }else{
                $model->image_icon = NULL;
              }
              
              if($model->save())
                  return $this->redirect(['site/index']);
              }
      }
      return $this->render('add',[
        'model' => $model,
        'category' => $category,
      ]);
    }

    public function uploadFile(UploadedFile $file){
            
            $filename = md5(uniqid($file->baseName)).'.'.$file->extension;

            $file->saveAs(Yii::getAlias('@web').'img/'.$filename);

            return $filename;
    }

    public function uploadFileIcon(UploadedFile $icon){

            $fileicon = md5(uniqid($icon->baseName)).'.'.$icon->extension;

            $icon->saveAs(Yii::getAlias('@web').'images/'.$fileicon);

            return $fileicon;
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionRole(){

 /*     $admin = Yii::$app->authManager->createRole('admin');
      $admin->description = 'Администратор';
      Yii::$app->authManager->add($admin);
  
 
      $permit = Yii::$app->authManager->createPermission('createPost');
      $permit->description = 'Право входа в админку';
      Yii::$app->authManager->add($permit);
*/
      return 1232132;

    }

}

frontend/controllers/CategoryController.php
<?php

namespace frontend\controllers;

use common\models\Article;
use common\models\Category;
use yii\data\Pagination;
use yii\web\HttpException;

class CategoryController extends \yii\web\Controller
{
    public function actionIndex($nick)
    {
        $category = Category::findOne(['nick' => $nick]);

        if (empty( $category )) {
            throw new HttpException( 404, 'Сез эзләгән '.$nick.' бите табылмады' );
        } else {

            $id = $category->id;
            $article = Article::find()->where(['category_id' => $id])->orderBy( 'date DESC' );

            $count = $article->andWhere(['status' => 1])->count();

            $pagination = new Pagination(['totalCount' => $count, 'pageSize' => 36]);

            $articles = $article->offset($pagination->offset)->limit($pagination->limit)->all();
        }
        return $this->render('index',[
            'category' => $category,
            'articles' => $articles,
            'pagination' => $pagination


        ]);
    }




}

frontend/views/category/index.php
<?php
/* @var $this yii\web\View */


use yii\helpers\Url;
use yii\widgets\LinkPager;

$this->registerMetaTag(['name' => 'keywords', 'content' =>  $category->title .', бары тик саф татарча кинолар,сериаллар,мультфильмнар tatar4a.ru'  ]);
$this->registerMetaTag(['name' => 'description', 'content' =>  $category->title .', бары тик саф татарча кинолар,сериаллар,мультфильмнар tatar4a.ru'  ]);

$this->title = $category->title;
?>
<!-- /w3l-medile-movies-grids -->
<div class="general-agileits-w3l">
    <div class="w3l-medile-movies-grids">

        <!-- /movie-browse-agile -->

        <div class="movie-browse-agile">
            <!--/browse-agile-w3ls -->
            <div class="browse-agile-w3ls general-w3ls">
                <div class="container">
                    <h3 class="head"><?= $category->title ?></h3>
                    <div class="grid_3 grid_4 w3layouts">
                        <div class="contact-agile">
                            <?php foreach ($articles as $article): ?>
                                <div class="col-md-2 w3l-movie-gride-agile" style="height: 350px;">
                                    <a href="<?= Url::toRoute(['site/video', 'id' => $article->id]); ?>" class="hvr-shutter-out-horizontal"><img src="<?= $article->getImage(); ?>" title="<?= $article->title ?>" alt="" style="width: 177px;height: 265px;"/>
                                        <div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
                                    </a>
                                    <div class="mid-1">
                                        <div class="w3l-movie-text">
                                            <h6><a href="<?= Url::toRoute(['site/video', 'id' => $article->id]); ?>"><?= $article->title ?></a></h6>
                                        </div>
                                        <div class="mid-2">

                                            <p><?= $article->film_date; ?></p>
                                            <div class="block-stars">
                                                <ul class="w3l-ratings">
                                                    <li><a class="s-facebook"><i class="fa fa-eye"></i></a></li> <?= $article->viewed; ?>
                                                </ul>
                                            </div>
                                            <div class="clearfix"></div>
                                        </div>

                                    </div>
                                    <?php if($article->new == 1):?>
                                        <div class="ribben">
                                            <p>NEW</p>
                                        </div>
                                    <?php endif; ?>
                                </div>

                            <?php endforeach; ?>

                            <div class="clearfix"> </div>
                        </div>
                    </div>
                </div>

                <!--//browse-agile-w3ls -->
                <div class="blog-pagenat-wthree">

                    <?php
                    echo LinkPager::widget([
                        'pagination' => $pagination,
                    ]);
                    ?>
                </div>
            </div>
            <!-- //movie-browse-agile -->
        </div>
    </div>
</div>
</div>
<!-- //w3l-medile-movies-grids -->
</div>
<!-- //comedy-w3l-agileits -->