backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\User;
use common\models\Article;
use common\models\Category;
use yii\web\UploadedFile;
use common\models\File;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['logout','index', 'video','add','delete','file','add-file'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['login', 'error','role'],
                        'allow' => true,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $articles = Article::find()->orderBy( 'id DESC')->all();

        return $this->render('index', [
            'articles' => $articles,
        ]);
    }

    public function actionDelete($id = false)
    {
        if (isset($id)) {
            if (Article::deleteAll(['in', 'id', $id])) {
                $this->redirect(['index']);
            }
        } else {
            $this->redirect(['index']);
        }
    }



    public function actionVideo($id)
    {

        $files = File::find()->where(['article_id' => $id])->all();
  
        $category = Category::find()->all();

        $article = Article::findOne($id);

        if($article->load(Yii::$app->request->post())){
            if($article->save())
                return $this->redirect(['site/index']);
                
      }

        return $this->render('video', [
            'article' => $article,
            'category' => $category,
            'files' => $files,
        ]);
    }

    public function actionFile($id){

      $files = File::find()->where(['article_id' => $id])->all();

      $article = File::find()->where(['id' => $id])->one();


      return $this->render('file',[
        'files' => $files,
        'article' => $article,
      ]);
    }

    public function actionAddFile($id){
      
        $model = new File();

        $model->article_id = $id;

        $model->date = date('Y-m-d');

        if($model->load(Yii::$app->request->post())){
          if($model->save()){
            return $this->redirect(['site/file','id'=> $id]);
          }
        }

      return $this->render('add-file',[
        'model' => $model,
      ]);
    }

    public function actionAdd(){

      
      $category = Category::find()->all();

      $model = new Article();
      $model->date = date('Y-m-d');
      $model->viewed = 0;
      if($model->load(Yii::$app->request->post())){
         if($model->validate()){
            $file = UploadedFile::getInstance($model,'image');
              if(file_exists($file)){
                $model->saveImage($this->uploadFile($file));
              }else{
                $model->image = NULL;
              }

              $icon = UploadedFile::getInstance($model,'image_icon');

              if(file_exists($icon)){
                $model->saveImageIcon($this->uploadFileIcon($icon));
              }else{
                $model->image_icon = NULL;
              }
              
              if($model->save())
                  return $this->redirect(['site/index']);
              }
      }
      return $this->render('add',[
        'model' => $model,
        'category' => $category,
      ]);
    }

    public function uploadFile(UploadedFile $file){
            
            $filename = md5(uniqid($file->baseName)).'.'.$file->extension;

            $file->saveAs(Yii::getAlias('@web').'img/'.$filename);

            return $filename;
    }

    public function uploadFileIcon(UploadedFile $icon){

            $fileicon = md5(uniqid($icon->baseName)).'.'.$icon->extension;

            $icon->saveAs(Yii::getAlias('@web').'images/'.$fileicon);

            return $fileicon;
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionRole(){

 /*     $admin = Yii::$app->authManager->createRole('admin');
      $admin->description = 'Администратор';
      Yii::$app->authManager->add($admin);
  
 
      $permit = Yii::$app->authManager->createPermission('createPost');
      $permit->description = 'Право входа в админку';
      Yii::$app->authManager->add($permit);
*/
      return 1232132;

    }

}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use app\models\CommentForm;
use common\models\Article;
use common\models\Raits;

use common\models\Rating;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\File;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm; 
use frontend\models\ContactForm;
use yii\web\HttpException;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {


        $kino = Article::find()->where( ['category_id' => 1] )->andWhere( ['status' => 1] )->orderBy( 'date DESC' )->limit( 12 )->all();
        $serial = Article::find()->where( ['category_id' => 2] )->andWhere( ['status' => 1] )->orderBy( 'date DESC' )->limit( 12 )->all();
        $animacionnij = Article::find()->where( ['category_id' => 3] )->andWhere( ['status' => 1] )->orderBy( 'date DESC' )->limit( 12 )->all();

        return $this->render( 'index', [
            'kino' => $kino,
            'serial' => $serial,
            'animacionnij' => $animacionnij,
        ] );
    }


    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load( Yii::$app->request->post() ) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render( 'login', [
                'model' => $model,
            ] );
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load( Yii::$app->request->post() )) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login( $user )) {
                    return $this->goHome();
                }
            }
        }

        return $this->render( 'signup', [
            'model' => $model,
        ] );
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load( Yii::$app->request->post() ) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash( 'success', 'Check your email for further instructions.' );

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash( 'error', 'Sorry, we are unable to reset password for the provided email address.' );
            }
        }

        return $this->render( 'requestPasswordResetToken', [
            'model' => $model,
        ] );
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm( $token );
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException( $e->getMessage() );
        }

        if ($model->load( Yii::$app->request->post() ) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash( 'success', 'New password saved.' );

            return $this->goHome();
        }

        return $this->render( 'resetPassword', [
            'model' => $model,
        ] );
    }


    public function actionVideo($id)
    {


        $article = Article::findOne( $id );

        if (empty( $article )) {
            throw new HttpException( 404, 'Сез эзләгән фильм табылмады.' );
        } else {


            $comments = $article->getArticleComments();
            $commentForm = new CommentForm();

            $files = File::find()->where(['article_id' => $id])->andWhere(['status' => 1])->all();

            $article->viewed += 1;
            $article->save( false );

            //выбираем все голоса по данной записи
            $rating = Rating::find()->where( ['article_id' => $id] )->all();
            if (count( $rating ) > 0) {
                $allRaits = Rating::find()->where( ['article_id' => $id] )->select( 'rating' );
                $allUsers = $allRaits->count();//сумма всех учетных записей пользователей к дан. материалу (1а запись - 1 пользователь)
                $sumVotes = $allRaits->sum( 'rating' );//сумма всех оценок пользователей к дан. материалу
                $totalRating = round( $sumVotes / $allUsers, 2 );// округляем до сотых
            } else $totalRating = 0;

        }


        return $this->render( 'video', [
            'article' => $article,
            'comments' => $comments,
            'commentForm' => $commentForm,
            'rating' => $rating,
            'sum' => $totalRating,
            'files' => $files,

        ] );
    }

    public function actionStars(){
        $model = new Rating();

        $user  = Rating::find()->where(['user_id' => Yii::$app->user->identity->id])->andWhere(['article_id' => $_GET['id']])->all();
        if(!$user){
            $model->rating = $_GET['rating'];
            $model->article_id = $_GET['id'];
            $model->user_id = $_GET['idUser'];
            if($model->save()){
                Yii::$app->session->setFlash( 'stars', 'Сезнен тавыш уңышлы гына җибәрелде' );
                return true;
            }
        }else {
            Yii::$app->session->setFlash( 'stars', 'Сезнен инде тавыш бирдегез.' );
            return true;
        }

        return false;
    }

     public function actionDownload($id){
        $data = File::findOne($id);
        header("Cache-Control: public");
        header("Pragma: public");
        header("Content-Type: ".pathinfo($data->file, PATHINFO_EXTENSION));
        header("Content-Type: video/mp4");
        header("Content-Disposition: attachment; filename=".$data->title .".mp4;");
        header("Content-Length: ".filesize($data->file));
        header("Content-Transfer-Encoding: binary");
            return readfile($data->file);
    }


    public function actionComment($id)
    {

        $model = new CommentForm();

        if (Yii::$app->request->isPost) {
            $model->load( Yii::$app->request->post() );
            if ($model->saveComment( $id )) {
                Yii::$app->getSession()->setFlash( 'success', 'Сезнен фикер остэлде' );
                return $this->redirect( ['site/video', 'id' => $id] );
            }
        }
    }
}

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>

<div class="faq">
    <div class="container">
        <h3 class="head"><?= Html::encode($this->title) ?></h3>
        <p class="lead"><?= nl2br(Html::encode($message)) ?></p
    </div>
</div>

frontend/views/site/video.php
<?php


use kartik\rating\StarRating;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\JsExpression;
use common\widgets\NewWidget;

if(!Yii::$app->user->isGuest){
    $id = Yii::$app->user->identity->id;
}else{
    $id = 0;
}

//$this->registerMetaTag(['name' => 'keywords', 'content' =>  'Татарча фильм Татрча кино Татарча сериал Татарча мультфильм'  ]);
$this->registerMetaTag(['name' => 'description' , 'content' => $article->title .' Татарча фильм Татарча '. mb_strtolower($article->category->title)]);

$this->registerMetaTag(['name' => 'twitter:title' , 'content' => $article->title]);
$this->registerMetaTag(['name' => 'twitter:description' , 'content' => $article->title]);
$this->registerMetaTag(['name' => 'og:url' , 'content' => 'tatar4a.ru']);

$this->registerMetaTag(['property' => 'og:title' , 'content' => $article->title]);
$this->registerMetaTag(['property' => 'og:description' , 'content' => $article->title]);
$this->registerMetaTag(['property' => 'og:type' , 'content' => 'website']);
$this->registerMetaTag(['property' => 'og:url' , 'content' => 'tatar4a.ru']);



$this->title = $article->title;

?>

<!-- single -->
<div class="single-page-agile-main">
    <div class="container">
        <div class="single-page-agile-info">
            <div class="agileits-single-top">
                <ol class="breadcrumb">
                    <li><a href="/">Баш бит</a></li>
                    <li><?= $article->category->title ?></li>
                    <li class="active"><?= $article->title ?></li>

                </ol>
            </div>
            <div class="single-page-agile-info">
                <div class="show-top-grids-w3lagile">
                    <div class="col-sm-8 single-left">
                        <div class="song">

                            <div class="video-grid-single-page-agileits">
                                <div data-video="dLmKio67pVQ" id="video"><img src="<?= $article->getImageIcon(); ?>" alt="" class="img-responsive" style=" width: 1173px; height: 600px;"/></div>
                            </div>
                        </div>
                        <div class="w3-agile-about-text">
                            <div><h3>Фильм турында</h3></div>
                            <p><?= $article->text ?>
                            <?php if($article->description === NULL): ?>
                                </p>
                            <?php else: ?>
                                <?= $article->description ?></p>
                            <?php endif; ?>
                        </div>
                    <table id="table-breakpoint5">
                        <thead>
                        <tr>
                            <th>Исем:</th>
                            <th>Йөкләү:</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if (!empty( $files )): ?>
                            <?php foreach ($files as $file): ?>
                                <tr>
                                    <td><?= $file->title ?></td>
                                    <td><a href="<?= $file->file  ?>" target="_blank"><button type="button" class="btn btn-primary">Яндекс диск</button></a></td>
                                </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>
                                <td>-</td>
                                <td>-</td>
                                
                            </tr>
                        <?php endif; ?>

                    </table>
                    <div style="max-width: 1280px; margin: 0 auto;  text-align: center;">
                        <div style="padding-top: 4%;padding: 1em 1em;box-shadow: 0px 0 10px #C1C1C1 !important;margin: 1em 0 0 0;">
                   <h1>Рейтинг</h1>
                        <?= kartik\rating\StarRating::widget([
                            'name' => 'rating',
                            'value' => $sum,
                            'pluginOptions' => [
                                //'readonly' => true,
                                'showClear' => false,
                                'showCaption' => false,
                                'disabled' => Yii::$app->user->isGuest ? true : false,//для гостя блокируем кнопки
                                'stars' => 10,
                                'min' => 0,
                                'max' => 10,
                                'step' => 0.5,
                                'size' => 'lg',
                                'defaultCaption' => 'оценка {rating}',
                                'starCaptions' => [
                                    0 => 'Extremely Poor',
                                    1 => 'оценка 1',
                                    2 => 'оценка 2',
                                    3 => 'оценка 3',
                                    4 => 'оценка 4',
                                    5 => 'оценка 5',
                                    6 => 'оценка 6',
                                    7 => 'оценка 7',
                                    8 => 'оценка 8',
                                    9 => 'оценка 9',
                                    10 => 'оценка 10',
                                ],
                            ],
                            'pluginEvents' => [
                                //когда кликаем на звезды всплывает это событие, которое и обробатываем
                                'rating:change' => "function(event, value, caption) {
                        $.ajax({
                         url: '/site/stars',
                                    method:'get',
                                    data: {
                                        rating:value,
                                        id:". $article->id .",
                                        idUser:". $id ." 
                                        },
                                    dataType: 'json',
                                    success:function(data){
                                            location.reload();
                                         }
                                });
                                }"

                            ],
                        ]) ?>
                        <p>Уртача рейтинг - "<?= $sum ?>"  (Тавыш бирде "<?= count($rating) ?>" кеше)</p>
                    </div>
                        <div style="padding-top: 3%;padding: 1em 1em;box-shadow: 0px 0 10px #C1C1C1 !important;margin: 1em 0 0 0;">
        <h1>Дусларынга cөйләү </h1>
        <br><br>
    
        <input value="ВКонтакте" type="button" class="share_btn" data-social="vk"> 
        <input value="Facebook" type="button" class="share_btn" data-social="fb"> 
        <input value="Одноклассники" type="button" class="share_btn" data-social="ok"> 
        <input value="Twitter" type="button" class="share_btn" data-social="tw"> 
        <input value="Google+" type="button" class="share_btn" data-social="gp"> 
    </div>
</div>
                    <div class="clearfix"></div>
                    <div class="all-comments">
                        <div class="all-comments-info">
                            <?php if (!Yii::$app->user->isGuest): ?>
                            <a href="#">Comments</a>
                            <?php if (Yii::$app->session->getFlash( 'success' )): ?>
                                <div class="alert alert-success" role="alert">
                                    <?= Yii::$app->session->getFlash( 'success' ); ?>
                                </div>
                            <?php endif; ?>
                            <div class="agile-info-wthree-box">
                                <?php $form = \yii\widgets\ActiveForm::begin( [
                                    'action' => ['site/comment', 'id' => $article->id],
                                ] ); ?>

                                <?= $form->field( $commentForm, 'comment' )->textarea( ['placeholder' => 'Message'] )->label( false ) ?>
                                <?= Html::submitButton( 'Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button'] ) ?>
                                <div class="clearfix"></div>

                                <?php \yii\widgets\ActiveForm::end(); ?>

                            </div>
                        </div>
                        <div class="media-grids">
                            <?php else: ?>
                                <div class="alert alert-success" role="alert">
                                    <p>Бары тик <strong><a href="/auth/login">АВТОРИЗАЦИЯ</a></strong> үткән
                                        кулланучылар гына фикер калдыра ала. </p>
                                </div>
                            <?php endif; ?>
                            <?php if (!empty( $comments )): ?>
                                <h3>Фикерләр(<?= count( $comments ) ?>)</h3>
                                <?php foreach ($comments as $comment): ?>
                                    <div class="media-grids">
                                        <div class="media">

                                            <div class="media-left">

                                                <img src="/images/user.jpg" title="One movies" alt=" "/>

                                            </div>
                                            <div class="media-body">

                                                <p><?= $comment->text; ?></p>
                                                <span>Автор :<a
                                                        href="#"> <?= $comment->user->username; ?> </a><?= $comment->getDate(); ?></span>
                                            </div>
                                        </div>
                                    </div>


                                <?php endforeach; ?>
                            <?php else: ?>
                                <div class="alert alert-success" role="alert">
                                    <p>Кызганычка каршы бу бүлектә әлегә фикерләр юк</p>
                                </div>
                            <?php endif; ?>

                        </div>
                    </div>
                </div>


                <div class="clearfix"></div>
                <?= NewWidget::widget() ?>
            </div>
        </div>
        <!-- //movie-browse-agile -->


    </div>
    <!-- //w3l-latest-movies-grids -->
</div>
</div>
<!-- //w3l-medile-movies-grids -->